// <auto-generated />
using System;
using EllosPratas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EllosPratas.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20251019212759_AdicionandoAlteracaoEmVendas")]
    partial class AdicionandoAlteracaoEmVendas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EllosPratas.Models.CaixaModel", b =>
                {
                    b.Property<int>("id_caixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_caixa"));

                    b.Property<DateTime>("data_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_fechamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_funcionario")
                        .HasColumnType("int");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<string>("observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_caixa");

                    b.HasIndex("id_funcionario");

                    b.HasIndex("id_loja");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("EllosPratas.Models.CategoriaModel", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome_categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("EllosPratas.Models.CidadeModel", b =>
                {
                    b.Property<int>("id_cidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cidade"));

                    b.Property<int>("id_estado")
                        .HasColumnType("int");

                    b.Property<string>("nome_cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cidade");

                    b.HasIndex("id_estado");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("EllosPratas.Models.ClienteModel", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EllosPratas.Models.DescontoModel", b =>
                {
                    b.Property<int>("id_desconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_desconto"));

                    b.Property<bool>("ativo_desconto")
                        .HasColumnType("bit");

                    b.Property<string>("nome_desconto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipo_desconto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("valor_desconto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_desconto");

                    b.ToTable("Descontos");
                });

            modelBuilder.Entity("EllosPratas.Models.EnderecoModel", b =>
                {
                    b.Property<int>("id_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_endereco"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_cidade")
                        .HasColumnType("int");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_endereco");

                    b.HasIndex("id_cidade");

                    b.HasIndex("id_loja")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("EllosPratas.Models.EstadoModel", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<string>("nome_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("EllosPratas.Models.EstoqueModel", b =>
                {
                    b.Property<int>("id_estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estoque"));

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id_estoque");

                    b.HasIndex("id_produto")
                        .IsUnique();

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("EllosPratas.Models.FormaPagamentoModel", b =>
                {
                    b.Property<int>("id_forma_pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_forma_pagamento"));

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_nivel_acesso")
                        .HasColumnType("int");

                    b.Property<int>("id_permissao")
                        .HasColumnType("int");

                    b.Property<string>("nome_forma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_forma_pagamento");

                    b.HasIndex("id_nivel_acesso");

                    b.HasIndex("id_permissao");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("EllosPratas.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("id_funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_funcionario"));

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_admissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<int>("id_nivel_acesso")
                        .HasColumnType("int");

                    b.Property<string>("nome_funcionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_funcionario");

                    b.HasIndex("id_loja");

                    b.HasIndex("id_nivel_acesso");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("EllosPratas.Models.ItensVendaModel", b =>
                {
                    b.Property<int>("id_item_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_item_venda"));

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("id_venda")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_item_venda");

                    b.HasIndex("id_produto");

                    b.HasIndex("id_venda");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("EllosPratas.Models.LojaModel", b =>
                {
                    b.Property<int>("id_loja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_loja"));

                    b.Property<string>("id_endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_loja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_loja");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("EllosPratas.Models.MovimentacaoCaixaModel", b =>
                {
                    b.Property<int>("id_movimentacao_caixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_movimentacao_caixa"));

                    b.Property<DateTime>("data_movimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_caixa")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_movimentacao_caixa");

                    b.HasIndex("id_caixa");

                    b.ToTable("MovimentacaoCaixa");
                });

            modelBuilder.Entity("EllosPratas.Models.NivelAcessoModel", b =>
                {
                    b.Property<int>("id_nivel_acesso_permissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nivel_acesso_permissao"));

                    b.Property<int>("id_nivel_acesso")
                        .HasColumnType("int");

                    b.Property<int>("id_permissao")
                        .HasColumnType("int");

                    b.Property<decimal?>("valor_adicional")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_nivel_acesso_permissao");

                    b.ToTable("NiveisAcesso");
                });

            modelBuilder.Entity("EllosPratas.Models.NivelAcessoPermissaoModel", b =>
                {
                    b.Property<int>("id_nivel_acesso_permissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nivel_acesso_permissao"));

                    b.Property<int>("id_nivel_acesso")
                        .HasColumnType("int");

                    b.Property<int>("id_permissao")
                        .HasColumnType("int");

                    b.Property<decimal?>("valor_adicional")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_nivel_acesso_permissao");

                    b.HasIndex("id_nivel_acesso");

                    b.HasIndex("id_permissao");

                    b.ToTable("NivelAcessoPermissoes");
                });

            modelBuilder.Entity("EllosPratas.Models.PagamentoModel", b =>
                {
                    b.Property<int>("id_pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagamento"));

                    b.Property<string>("bandeira_cartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_desconto")
                        .HasColumnType("int");

                    b.Property<int>("id_forma_pagamento")
                        .HasColumnType("int");

                    b.Property<int>("id_venda")
                        .HasColumnType("int");

                    b.Property<int>("quantidade_parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_parcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_pagamento");

                    b.HasIndex("id_desconto");

                    b.HasIndex("id_forma_pagamento");

                    b.HasIndex("id_venda")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("EllosPratas.Models.PermissaoModel", b =>
                {
                    b.Property<int>("id_permissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_permissao"));

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_permissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_permissao");

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("EllosPratas.Models.ProdutosModel", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_produto"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<byte[]>("imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nome_produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_produto");

                    b.HasIndex("id_categoria");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EllosPratas.Models.VendasModel", b =>
                {
                    b.Property<int>("id_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_venda"));

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_caixa")
                        .HasColumnType("int");

                    b.Property<int?>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_funcionario")
                        .HasColumnType("int");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_venda");

                    b.HasIndex("id_caixa");

                    b.HasIndex("id_cliente");

                    b.HasIndex("id_funcionario");

                    b.HasIndex("id_loja");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("EllosPratas.Models.CaixaModel", b =>
                {
                    b.HasOne("EllosPratas.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Caixas")
                        .HasForeignKey("id_funcionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.LojaModel", "Loja")
                        .WithMany("Caixas")
                        .HasForeignKey("id_loja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("EllosPratas.Models.CidadeModel", b =>
                {
                    b.HasOne("EllosPratas.Models.EstadoModel", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("EllosPratas.Models.EnderecoModel", b =>
                {
                    b.HasOne("EllosPratas.Models.CidadeModel", "Cidade")
                        .WithMany("Enderecos")
                        .HasForeignKey("id_cidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.LojaModel", "Loja")
                        .WithOne("Endereco")
                        .HasForeignKey("EllosPratas.Models.EnderecoModel", "id_loja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("EllosPratas.Models.EstoqueModel", b =>
                {
                    b.HasOne("EllosPratas.Models.ProdutosModel", "Produto")
                        .WithOne("Estoque")
                        .HasForeignKey("EllosPratas.Models.EstoqueModel", "id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EllosPratas.Models.FormaPagamentoModel", b =>
                {
                    b.HasOne("EllosPratas.Models.NivelAcessoModel", "NivelAcesso")
                        .WithMany()
                        .HasForeignKey("id_nivel_acesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.PermissaoModel", "Permissao")
                        .WithMany()
                        .HasForeignKey("id_permissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcesso");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("EllosPratas.Models.FuncionarioModel", b =>
                {
                    b.HasOne("EllosPratas.Models.LojaModel", "Loja")
                        .WithMany("Funcionarios")
                        .HasForeignKey("id_loja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.NivelAcessoModel", "NivelAcesso")
                        .WithMany("Funcionarios")
                        .HasForeignKey("id_nivel_acesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("EllosPratas.Models.ItensVendaModel", b =>
                {
                    b.HasOne("EllosPratas.Models.ProdutosModel", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.VendasModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("id_venda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EllosPratas.Models.MovimentacaoCaixaModel", b =>
                {
                    b.HasOne("EllosPratas.Models.CaixaModel", "Caixa")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("id_caixa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixa");
                });

            modelBuilder.Entity("EllosPratas.Models.NivelAcessoPermissaoModel", b =>
                {
                    b.HasOne("EllosPratas.Models.NivelAcessoModel", "NivelAcesso")
                        .WithMany("NivelAcessoPermissoes")
                        .HasForeignKey("id_nivel_acesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.PermissaoModel", "Permissao")
                        .WithMany("NivelAcessoPermissoes")
                        .HasForeignKey("id_permissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcesso");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("EllosPratas.Models.PagamentoModel", b =>
                {
                    b.HasOne("EllosPratas.Models.DescontoModel", "Desconto")
                        .WithMany("Pagamentos")
                        .HasForeignKey("id_desconto");

                    b.HasOne("EllosPratas.Models.FormaPagamentoModel", "FormaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("id_forma_pagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.VendasModel", "Venda")
                        .WithOne("Pagamento")
                        .HasForeignKey("EllosPratas.Models.PagamentoModel", "id_venda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desconto");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EllosPratas.Models.ProdutosModel", b =>
                {
                    b.HasOne("EllosPratas.Models.CategoriaModel", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EllosPratas.Models.VendasModel", b =>
                {
                    b.HasOne("EllosPratas.Models.CaixaModel", "Caixa")
                        .WithMany()
                        .HasForeignKey("id_caixa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.ClienteModel", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("id_cliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EllosPratas.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Vendas")
                        .HasForeignKey("id_funcionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EllosPratas.Models.LojaModel", "Loja")
                        .WithMany("Vendas")
                        .HasForeignKey("id_loja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("EllosPratas.Models.CaixaModel", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("EllosPratas.Models.CategoriaModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("EllosPratas.Models.CidadeModel", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("EllosPratas.Models.ClienteModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("EllosPratas.Models.DescontoModel", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("EllosPratas.Models.EstadoModel", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("EllosPratas.Models.FormaPagamentoModel", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("EllosPratas.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Caixas");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("EllosPratas.Models.LojaModel", b =>
                {
                    b.Navigation("Caixas");

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Funcionarios");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("EllosPratas.Models.NivelAcessoModel", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("NivelAcessoPermissoes");
                });

            modelBuilder.Entity("EllosPratas.Models.PermissaoModel", b =>
                {
                    b.Navigation("NivelAcessoPermissoes");
                });

            modelBuilder.Entity("EllosPratas.Models.ProdutosModel", b =>
                {
                    b.Navigation("Estoque");

                    b.Navigation("ItensVenda");
                });

            modelBuilder.Entity("EllosPratas.Models.VendasModel", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
